apiVersion: apps/v1
kind: Deployment
metadata:
  name: athena-sts-demo
  namespace: springboot-aws-demo-ns
  labels:
    app: athena-sts-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: athena-sts-demo
  template:
    metadata:
      labels:
        app: athena-sts-demo
    spec:
      containers:
        - name: athena-sts-demo
          image: gourabp/gp-aws-athena-sts
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          volumeMounts:
            - name: aws-credentials
              mountPath: "/root/.aws"
              readOnly: true  # Ensure the mounted volume is read-only
      volumes:
        - name: aws-credentials
          secret:
            secretName: aws-credentials
      imagePullSecrets:
        - name: docker-secrets
