athena-source:
  env: 'local'
  camelAthenaTargetDef:
     region: "us-east-1"
     profile: 'jagyiamgpathenauser'
     account: '682596026257'
     roleName: 'gp-athenafull-role'
     roleSessionName: 'AssumeRoleSession'
     roleArn: 'arn:aws:iam::682596026257:role/gp-athenafull-role'
     outputS3: 's3://gp-result-athena1/result1/'
     workgroup: 'primary'
     db: 'mydb'
     query: 'SELECT * FROM mydb.houses limit 4'
     sessionDurationSeconds: 3600
     athenaClientId: "demo-athena-client"
     delay: 1000
     repeatCount: 3
